# global parameters
model_name: attbilstm  # 'han', 'fasttext', 'attbilstm', 'textcnn', 'transformer'
                       # refer to README.md for more info about each model

# dataset parameters
dataset: instance_severity  # 'ag_news', 'dbpedia', 'yelp_review_polarity', 'yelp_review_full', 'yahoo_answers', 'amazon_review_polarity', 'amazon_review_full'
                  # refer to README.md for more info about each dataset
dataset_path: E:/working_incident_data/cleaned_data/classification_datasets/severity/balanced/binary_class/  # folder with dataset
output_path: E:/working_incident_data/cleaned_data/classification_datasets/severity/balanced/binary_class/processed_vec/  # folder with data files saved by preprocess.py

# preprocess parameters
word_limit: 500
min_word_count: 5

# word embeddings parameters
emb_pretrain: False  # false: initialize embedding weights randomly
                    # true: load pre-trained word embeddings
emb_folder: E:/saved_models/word2vec/  # only makes sense when `emb_pretrain: True`
emb_filename: glove.6B.300d.txt  # only makes sense when `emb_pretrain: True`
emb_size: 256  # word embedding size
               # only makes sense when `emb_pretrain: False`
fine_tune_word_embeddings: True  # fine-tune word embeddings?

# model parameters
rnn_size: 64  # bi-RNN size
rnn_layers: 1  # number of layers in bi-RNN
dropout: 0.3  # dropout

# checkpoint saving parameters
checkpoint_path: E:/saved_models/classification_tasks/ckpts/word2vec/severity/  # path to save checkpoints, null if never save checkpoints
checkpoint_basename: checkpoint_attbilstm_severity  # basename of the checkpoint

# training parameters
start_epoch: 0  # start at this epoch
batch_size: 64  # batch size
lr: 0.001  # learning rate
lr_decay: 0.9  # a factor to multiply learning rate with (0, 1)
workers: 4  # number of workers for loading data in the DataLoader
num_epochs: 2  # number of epochs to run
grad_clip: null  # clip gradients at this value, null if never clip gradients
print_freq: 500  # print training status every __ batches
checkpoint: null  # path to model checkpoint, null if none
# tensorboard
tensorboard: True  # enable tensorboard or not?
log_dir: E:/saved_models/classification_tasks/logs/word2vec/severity/  # folder to save logs for tensorboard, only makes sense when `tensorboard: True`
